# Name of output folder
sample_name: example_egfr_single_read_run

# Input FASTQ files. Can be a (zipped) FASTQ file or a folder containing (zipped) FASTQ files
input_fastq: data/example_egfr_single_cluster.fastq

# Reference genome
reference_fasta: "data/example_egfr_reference.fasta"

# BED file containing intervals with regions that are going to be analysed
targets_bed: data/example_egfr_amplicon.bed


############################
######### Optional #########
############################
#
# Max differences between UMI in read and UMI pattern
umi_errors: 3

# Min number of reads required for a consensus read
min_reads_per_cluster: 20

# Max number of 1D used for a consensus read
max_reads_per_cluster: 60

# Min overlap with target region
min_overlap: 0.90

# Balance forward and reverse 1D reads in clusters
balance_strands: True

# Medaka model used to compute consensus reads
medaka_model: "r1041_e82_400bps_sup_g615"

# Forward tail of primer (Ftail...UMI...primer)
fwd_context: "GTATCGTGTAGAGACTGCGTAGG"

# Reverse tail of primer (Rtail...UMI...primer)
rev_context: "AGTGATCGAGTCAGTGCGAGTG"

# Forward UMI (Ftail...UMI...primer) The inside sequence can be appended to the UMI sequence to increase specificity, e.g. UMI then 4bases of primer: TTTVVVVTTVVVVTTVVVVTTVVVVTTTaggt
fwd_umi: "TTTVVVVTTVVVVTTVVVVTTVVVVTTT"

# Reverse UMI (Rtail...UMI...primer) The inside sequence can be appended to the UMI sequence to increase specificity, e.g. UMI then 4bases of primer: TTTVVVVTTVVVVTTVVVVTTVVVVTTTaggt
rev_umi: "AAABBBBAABBBBAABBBBAABBBBAAA"

# Minimum combined UMI length
min_length: 40

# Maximum combined UMI length
max_length: 60

# should the fastq reads be length and quality filtered?
filter_reads: False

# fastq min read length (if filter_reads is set to true)
min_read_len: 100

# fastq min mean read quality score (if filter_reads is set to true)
min_mean_qual: 70

# Variant filtering options for varscan
varscan_params: '--variants 1 --output-vcf 1 --min-coverage 8 --min-avg-qual 0 --min-var-freq 0.001 --strand-filter 0 --p-value 1 --min-reads2 2'


