name: ont_umi_pipeline
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - snakemake
  - minimap2
  - samtools
  - tabix
  - seqkit
  - pysam
  - bedtools
  - vsearch
  - varscan
  - medaka
  - pip
